# Generated by Django 5.1.1 on 2024-11-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utenti',
            table='utenti',
        ),
    ]
