# Generated by Django 5.1.1 on 2024-11-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge_Login', '0003_persona'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utenti',
            table=None,
        ),
    ]
