# Generated by Django 5.1.1 on 2024-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge_Login', '0004_alter_utenti_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='aa_dha',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='aa_epa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='albumin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='bilirubin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='biological_age',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='cardiovascular_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='chronological_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='creatinine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='d_roms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ferritin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='homa_test',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='obri_index',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='osi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='uric_acid',
            field=models.FloatField(null=True),
        ),
    ]
