# Generated by Django 5.1.1 on 2024-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge_Login', '0006_remove_persona_eosi_remove_persona_albumina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='biological_age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
